title: JR Kayle Gamundoy
# logo: path_to_your_headshot_img_here (ex: asset/img/profile_picture.png
# description: text that appears below your logo/profile picture (ex: Data Scientist)
show_downloads: True
theme: jekyll-theme-minimal
